
-- https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/
-- https://www.commandprompt.com/education/how-do-i-create-an-identity-column-in-postgresql/

-- PostgreSQL identity column
[name] TYPE GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY[ ( seq_option ) ]

CREATE TABLE commandprompt_example(
id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
blog_name TEXT
);

INSERT INTO commandprompt_example(blog_name)
VALUES ('blog 1'),
('blog 2');

SELECT * FROM commandprompt_example;

INSERT INTO commandprompt_example(id, blog_name)
VALUES (3, 'blog 3');


CREATE TABLE commandprompt_example_1(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
blog_name TEXT
);

INSERT INTO commandprompt_example_1(blog_name)
VALUES ('blog 1'),
('blog 2')
RETURNING *;

INSERT INTO commandprompt_example_1(id, blog_name)
VALUES (3, 'blog 3');